name: The Life of Me
favicon: null
layout_spectrum: 0.6160043
typography_spectrum: 0.2475832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030106'
    - '#FFC8FF'
    - '#45386D'
    - '#AEA0FF'
    - '#B36EA4'
  brandStrength: 0.7277121
  lightness: 0.6879699
  saturation: 0.2497315
  rhythmicContrast: 0.3743287
purpose: []
