name: The Life of Me
favicon: null
layout_spectrum: 0.6160043
typography_spectrum: 0.00233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dcdcdc'
    - '#424242'
    - '#848484'
    - '#232323'
  brandStrength: 0.1875
  lightness: 0.6879699
  saturation: 0.2497315
  rhythmicContrast: 0.3743287
purpose: []
