name: The Life of Me
favicon: null
layout_spectrum: 0.82008
typography_spectrum: 0.03216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#04070c'
    - '#a4c6f3'
    - '#3b3c36'
    - '#979a93'
  brandStrength: 0.1875
  lightness: 0.6879699
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
