layout_spectrum: 0.6160043
color:
  saturation: 0.2497315
  lightness: 0.6879699
  brandStrength: 0.7277121
  brandColors:
    - '#030106'
    - '#FFC8FF'
    - '#45386D'
    - '#AEA0FF'
    - '#B36EA4'
  rhythmicContrast: 0.3743287
typography_spectrum: 0.2475832
name: The Life of Me
